# Generated by Django 4.0.4 on 2022-06-13 16:48

import dataclasses
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, verbose_name='name')),
                ('price', models.FloatField(null=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=220, null=True)),
                ('amount', models.IntegerField(verbose_name=dataclasses.field)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=60)),
                ('products', models.ManyToManyField(related_name='product_category', to='tienda.product')),
            ],
        ),
    ]
