# Generated by Django 4.0.4 on 2022-06-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
    ]
