# Generated by Django 4.0.4 on 2022-06-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_category_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(related_name='product_category', to='tienda.product'),
        ),
    ]
